on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v6
      - id: foo
        uses: phodigere/hello-world-composite-action@9c1ec43fb87733503d802978b0474fb651e24d0a
        with:
          who-to-greet: 'The only one: Ekameva'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
